-- +goose Up
CREATE TABLE orders
(
	"id" bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"time" timestamp without time zone NOT NULL,
	"comment" character varying,
	"address_id" bigint NOT NULL REFERENCES address (id),
	"created_at" timestamp without time zone NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS orders;