-- +goose Up
DROP TABLE IF EXISTS address;

CREATE TABLE address
(
    "full_address" character varying NOT NULL,
    "geo_lat" real,
    "geo_lon" real,
    "id" bigint NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT address_unique UNIQUE (full_address, geo_lat, geo_lon)
);

-- +goose Down
DROP TABLE IF EXISTS address;
