-- +goose Up
DROP TABLE IF EXISTS address;

CREATE TABLE address
(
    "full_address" character varying NOT NULL,
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- +goose Down
DROP TABLE IF EXISTS address;
