-- +goose Up
CREATE TABLE workshops
(
    "id" bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying,
    "address_id" bigint NOT NULL REFERENCES address (id),
	"created_at" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE works
(
    "workshop_id" bigint NOT NULL REFERENCES workshops (id),
    "order_id" bigint NOT NULL REFERENCES orders (id),
	"start_at" timestamp without time zone,
    "status" smallint NOT NULL,
    PRIMARY KEY (order_id)
);

-- +goose Down
DROP TABLE works;
DROP TABLE workshops;
