// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: geo-suggest.proto

package geo_suggest_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddressSuggestService_Suggest_FullMethodName = "/geo_suggest_pb.AddressSuggestService/Suggest"
)

// AddressSuggestServiceClient is the client API for AddressSuggestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressSuggestServiceClient interface {
	Suggest(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SuggestResponse, error)
}

type addressSuggestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressSuggestServiceClient(cc grpc.ClientConnInterface) AddressSuggestServiceClient {
	return &addressSuggestServiceClient{cc}
}

func (c *addressSuggestServiceClient) Suggest(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestResponse)
	err := c.cc.Invoke(ctx, AddressSuggestService_Suggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressSuggestServiceServer is the server API for AddressSuggestService service.
// All implementations must embed UnimplementedAddressSuggestServiceServer
// for forward compatibility.
type AddressSuggestServiceServer interface {
	Suggest(context.Context, *QueryRequest) (*SuggestResponse, error)
	mustEmbedUnimplementedAddressSuggestServiceServer()
}

// UnimplementedAddressSuggestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddressSuggestServiceServer struct{}

func (UnimplementedAddressSuggestServiceServer) Suggest(context.Context, *QueryRequest) (*SuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suggest not implemented")
}
func (UnimplementedAddressSuggestServiceServer) mustEmbedUnimplementedAddressSuggestServiceServer() {}
func (UnimplementedAddressSuggestServiceServer) testEmbeddedByValue()                               {}

// UnsafeAddressSuggestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressSuggestServiceServer will
// result in compilation errors.
type UnsafeAddressSuggestServiceServer interface {
	mustEmbedUnimplementedAddressSuggestServiceServer()
}

func RegisterAddressSuggestServiceServer(s grpc.ServiceRegistrar, srv AddressSuggestServiceServer) {
	// If the following call pancis, it indicates UnimplementedAddressSuggestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddressSuggestService_ServiceDesc, srv)
}

func _AddressSuggestService_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressSuggestServiceServer).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressSuggestService_Suggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressSuggestServiceServer).Suggest(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressSuggestService_ServiceDesc is the grpc.ServiceDesc for AddressSuggestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressSuggestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo_suggest_pb.AddressSuggestService",
	HandlerType: (*AddressSuggestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Suggest",
			Handler:    _AddressSuggestService_Suggest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geo-suggest.proto",
}
