// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geo-suggest.proto

package geo_suggest_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bound int32

const (
	Bound_country    Bound = 0
	Bound_region     Bound = 1
	Bound_area       Bound = 2
	Bound_city       Bound = 3
	Bound_settlement Bound = 4
	Bound_street     Bound = 5
	Bound_house      Bound = 6
	Bound_flat       Bound = 7
)

var Bound_name = map[int32]string{
	0: "country",
	1: "region",
	2: "area",
	3: "city",
	4: "settlement",
	5: "street",
	6: "house",
	7: "flat",
}

var Bound_value = map[string]int32{
	"country":    0,
	"region":     1,
	"area":       2,
	"city":       3,
	"settlement": 4,
	"street":     5,
	"house":      6,
	"flat":       7,
}

func (x Bound) String() string {
	return proto.EnumName(Bound_name, int32(x))
}

func (Bound) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5bc3976dd0a58c4f, []int{0}
}

type QueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	FromBound            Bound    `protobuf:"varint,2,opt,name=from_bound,json=fromBound,proto3,enum=geo_suggest_pb.Bound" json:"from_bound,omitempty"`
	ToBound              Bound    `protobuf:"varint,3,opt,name=to_bound,json=toBound,proto3,enum=geo_suggest_pb.Bound" json:"to_bound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bc3976dd0a58c4f, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetFromBound() Bound {
	if m != nil {
		return m.FromBound
	}
	return Bound_country
}

func (m *QueryRequest) GetToBound() Bound {
	if m != nil {
		return m.ToBound
	}
	return Bound_country
}

type SuggestResponse struct {
	Suggestions          []*SuggestResponse_Result `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SuggestResponse) Reset()         { *m = SuggestResponse{} }
func (m *SuggestResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestResponse) ProtoMessage()    {}
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bc3976dd0a58c4f, []int{1}
}

func (m *SuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestResponse.Unmarshal(m, b)
}
func (m *SuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestResponse.Marshal(b, m, deterministic)
}
func (m *SuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestResponse.Merge(m, src)
}
func (m *SuggestResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestResponse.Size(m)
}
func (m *SuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestResponse proto.InternalMessageInfo

func (m *SuggestResponse) GetSuggestions() []*SuggestResponse_Result {
	if m != nil {
		return m.Suggestions
	}
	return nil
}

type SuggestResponse_Result struct {
	Value                string            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SuggestResponse_Result) Reset()         { *m = SuggestResponse_Result{} }
func (m *SuggestResponse_Result) String() string { return proto.CompactTextString(m) }
func (*SuggestResponse_Result) ProtoMessage()    {}
func (*SuggestResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bc3976dd0a58c4f, []int{1, 0}
}

func (m *SuggestResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestResponse_Result.Unmarshal(m, b)
}
func (m *SuggestResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestResponse_Result.Marshal(b, m, deterministic)
}
func (m *SuggestResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestResponse_Result.Merge(m, src)
}
func (m *SuggestResponse_Result) XXX_Size() int {
	return xxx_messageInfo_SuggestResponse_Result.Size(m)
}
func (m *SuggestResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestResponse_Result proto.InternalMessageInfo

func (m *SuggestResponse_Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SuggestResponse_Result) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("geo_suggest_pb.Bound", Bound_name, Bound_value)
	proto.RegisterType((*QueryRequest)(nil), "geo_suggest_pb.QueryRequest")
	proto.RegisterType((*SuggestResponse)(nil), "geo_suggest_pb.SuggestResponse")
	proto.RegisterType((*SuggestResponse_Result)(nil), "geo_suggest_pb.SuggestResponse.Result")
	proto.RegisterMapType((map[string]string)(nil), "geo_suggest_pb.SuggestResponse.Result.DataEntry")
}

func init() {
	proto.RegisterFile("geo-suggest.proto", fileDescriptor_5bc3976dd0a58c4f)
}

var fileDescriptor_5bc3976dd0a58c4f = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x77, 0x92, 0x26, 0xd9, 0xbc, 0x4a, 0x77, 0x76, 0x70, 0x21, 0x14, 0xc1, 0xd2, 0x83,
	0x14, 0xc1, 0xb8, 0x54, 0x41, 0xf1, 0xe6, 0xb2, 0x82, 0x78, 0x33, 0x7b, 0xf3, 0x52, 0xa6, 0xc9,
	0x6b, 0x0c, 0xa6, 0x99, 0x76, 0xe6, 0x4d, 0xa1, 0xdf, 0xc1, 0xaf, 0xe0, 0x27, 0xf5, 0x22, 0x93,
	0xa4, 0xda, 0xf6, 0xa0, 0xde, 0xde, 0xfb, 0xcf, 0xfb, 0xcd, 0x9f, 0xff, 0xe3, 0xc1, 0x75, 0x89,
	0xea, 0x85, 0xb1, 0x65, 0x89, 0x86, 0xd2, 0x8d, 0x56, 0xa4, 0xc4, 0xa8, 0x44, 0xb5, 0xe8, 0xa5,
	0xc5, 0x66, 0x39, 0xfd, 0xce, 0xe0, 0xd1, 0x67, 0x8b, 0x7a, 0x9f, 0xe1, 0xd6, 0xa2, 0x21, 0xf1,
	0x18, 0x82, 0xad, 0xeb, 0x13, 0x36, 0x61, 0xb3, 0x38, 0xeb, 0x1a, 0xf1, 0x1a, 0x60, 0xa5, 0xd5,
	0x7a, 0xb1, 0x54, 0xb6, 0x29, 0x12, 0x6f, 0xc2, 0x66, 0xa3, 0xf9, 0x4d, 0x7a, 0xfa, 0x57, 0x7a,
	0xe7, 0x1e, 0xb3, 0xd8, 0x0d, 0xb6, 0xa5, 0xb8, 0x85, 0x4b, 0x52, 0x3d, 0xe3, 0xff, 0x8d, 0x89,
	0x48, 0xb5, 0xc5, 0xf4, 0x27, 0x83, 0xab, 0x87, 0xee, 0x35, 0x43, 0xb3, 0x51, 0x8d, 0x41, 0xf1,
	0x11, 0x86, 0x3d, 0x50, 0xa9, 0xc6, 0x24, 0x6c, 0xe2, 0xcf, 0x86, 0xf3, 0x67, 0xe7, 0x1f, 0x9d,
	0x51, 0x69, 0x86, 0xc6, 0xd6, 0x94, 0x1d, 0xa3, 0xe3, 0x1f, 0x0c, 0xc2, 0x4e, 0x77, 0x31, 0x77,
	0xb2, 0xb6, 0x78, 0x88, 0xd9, 0x36, 0xe2, 0x1e, 0x06, 0x85, 0x24, 0x99, 0x78, 0xad, 0xc7, 0xed,
	0xff, 0x79, 0xa4, 0xf7, 0x92, 0xe4, 0x87, 0x86, 0xf4, 0x3e, 0x6b, 0xe9, 0xf1, 0x1b, 0x88, 0x7f,
	0x4b, 0x82, 0x83, 0xff, 0x0d, 0x0f, 0xdb, 0x74, 0xe5, 0x1f, 0x6b, 0xef, 0xc8, 0xfa, 0x9d, 0xf7,
	0x96, 0x3d, 0x47, 0x08, 0xba, 0xc5, 0x0d, 0x21, 0xca, 0x95, 0x75, 0x3c, 0xbf, 0x10, 0x00, 0xa1,
	0xc6, 0xb2, 0x52, 0x0d, 0x67, 0xe2, 0x12, 0x06, 0x52, 0xa3, 0xe4, 0x9e, 0xab, 0xf2, 0x8a, 0xf6,
	0xdc, 0x17, 0x23, 0x00, 0x83, 0x44, 0x35, 0xae, 0xb1, 0x21, 0x3e, 0x70, 0xf3, 0x86, 0x34, 0x22,
	0xf1, 0x40, 0xc4, 0x10, 0x7c, 0x55, 0xd6, 0x20, 0x0f, 0x1d, 0xb0, 0xaa, 0x25, 0xf1, 0x68, 0x9e,
	0xc3, 0xcd, 0xfb, 0xa2, 0xd0, 0x68, 0x4c, 0x1f, 0xe8, 0x01, 0xf5, 0xae, 0xca, 0x51, 0x7c, 0x82,
	0xa8, 0x57, 0xc4, 0x93, 0xf3, 0xec, 0xc7, 0x47, 0x32, 0x7e, 0xfa, 0x8f, 0xcd, 0x4c, 0x2f, 0xee,
	0xae, 0xbf, 0x5c, 0xbd, 0x3c, 0x1d, 0x5a, 0x86, 0xed, 0x09, 0xbe, 0xfa, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x63, 0xaa, 0x76, 0xf8, 0x97, 0x02, 0x00, 0x00,
}
